### PR TITLE
FIFO: set the FifoQueue property to true when the queue name ends wit…

### PR DESCRIPTION
**Pull request by priordan83**
…h .fifo.

### CODE REVIEW

**Comment by priordan83** [comment]
AWS forces you to create FIFO queues with the suffix .fifo in the queue
name.  Just my opinion but if someone has named a queue with the .fifo
suffix I think we can safely assume that the queue is FIFO.

From Amazon docs:

"The name of a FIFO queue must end with the .fifo suffix. The suffix counts
towards the 80-character queue name limit. To determine whether a queue is
FIFO, you can check whether the queue name ends with the suffix."

http://docs.aws.amazon.com/AWSSimpleQueueService/latest/
SQSDeveloperGuide/FIFO-queues.html

**Comment by priordan83** [comment]
Any update on this, or would you prefer I fork my changes?

**Comment by jegesh** [comment]
Sorry it took me so long to back to this

**Comment by priordan83** [comment]
Any chance of getting this change in pip?

**Pull request merged**
